### ISSUE TITLE
Data extraction from GFF file - question w.r.t format and structure

### ISSUE THREAD

**Issue by NinaASB** [GralDispersionModel/GUI#84]
Hello,

I hope you can help me with a questions even if it is not a concrete issue with the code itself.

I would like to extract pointwise information from the gff file to understand the local wind situations.

I used the code from your 
https://github.com/GralDispersionModel/GUI/blob/main/src/Gral/GRALIO/IO_ReadGFF.cs
but translated to python.

To understand the gff information I tried to compare it with results from GRAL_Meteozeitreihe.dat.
My GRAL.geb:
2               !cell-size for cartesian wind field in GRAL in x-direction
2               !cell-size for cartesian wind field in GRAL in y-direction
1.0,1.01                !cell-size for cartesian wind field in GRAL in z-direction, streching factor for increasing cells heights with height
959                !number of cells for counting grid in GRAL in x-direction
609                !number of cells for counting grid in GRAL in y-direction
3                !Number of horizontal slices
1,                !Source groups to be computed seperated by a comma
699560                !West border of GRAL model domain [m]
701478                !East border of GRAL model domain [m]
5704574                !South border of GRAL model domain [m]
5705792                !North border of GRAL model domain [m]

The respective line from Receptor.dat:
18,700423.19,5705387.2,1.5,LB4,0

The wind situation considered:
235 Grad, 8.5 m/s, Stablity 4

Based on the above Data I tried to find the index for my receptor cell
So I computed based on the Receptor coordinates: 
(700423.19-699560 )/2 = 431.594999 -> Which I interpret as index in x direction as 430
(5705387.2 – 701478)/ = 406.6000 -> Which I interpret as index in y direction as 405 
First cell height 1, 2nd 1.01 so the cell index in z direction should be 1.

From the gff file I read Uk[430][405][1]= 4.792213439941407e-07  (I checked also the neighbouring cells). 
Yet in GRAL_Meteozeitreihe.dat File the Receptor shows an U value of  0.13.

What did I do wrong, e.g. with the indices? Or how do I have to transform the UK value, since e-7 ist extrem low?

What I also don’t understand is the given gff file direction with 0.610865.. which is neither grad nor rad?
NKK 221
NJJ 609
NII 959
Direction 0.6108652353286743
Speed 8.5
AK 4
Cellsize 2.0
header -1

and what does the TKE  Field mean?

I would be more than happy, if you could help me understand my findings.

**Comment by MarkusKuntner** [comment]
Here is an attempt to answer the questions compactly and (hopefully) sufficiently:

`Direction`
This is the direction in radiant, as used internally in GRAL. The direction in degrees is obtained as below:
Dir = 270-0,611*180/Pi = 235°: the direction is shuffled within the meteopgt.all sector width for flat terrain in GRAL

`File mode`
header == -1 -> default *.gff files (there are 2 further modes)

`Wind components`
u[][][], v[][][] and w[][][] components are stored as `int16` values (2 bytes per value) and scaled by a factor of 100 (unit  [cm/s])
This results in a range from 0 to +- 327.67 m/s with two decimal places. With this design we achieve a compact file format for the very large amounts of data contained in *.gff files.

`*.tke file` 
tke = Turbulent kinetic energy;  “*.tke” is an optional file within the zip container, if the k-eps model has been used (not the default mode). This file is only used internally in GRAL if the k-epsilon model is applied (this mode can be activated manually by a user defined control file).

The latest GUI (file V2109RC2.zip) can extract meteorological time series from GRAL *.gff files at arbitrary points, as well as GRAMM from *.wnd files.
https://github.com/GralDispersionModel/GUI/releases/tag/V2109RC2

Don’t hesitate to comment below if you have any further questions.
